### ISSUE TITLE
How do you connect a local Dappchain to the block explorer?

### ISSUE THREAD

**Issue by donfrigo** [loomnetwork/vue-block-explorer#9]
Having started the loom executable and getting
> Starting RPC HTTP server on tcp://127.0.0.1:9999 module=query-server 

I was trying to connect to it through the block explorer by modifying the App.vue file
` allowedUrls = [
    'http://127.0.0.1:9999',
    'https://prodwss2.delegatecall.com',
    'https://prodwss.delegatecall.com',
    'https://stagewss.delegatecall.com'
  ]`

but unfortunately no blocks show up. What am I doing wrong? Thanks!

**Comment by mattkanwisher** [comment]
Currently the blockexplorer is for delegatecall. We have a new branch for loom dAppchains that will be our end of the month

**Comment by donfrigo** [comment]
Okay, thank you for your prompt reply!
